#-----------------------------------
#MYFirst  github actions 
#
#-----------------------------------
name: Demo-actions
env:
   APPLICATION_NAME: "MyFlask"
   PACKAGE         : "flask_deploy_ver_${{ github.sha }}"
on: 
   push:
     branches: 
        - master 

jobs:
  my_testings:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: echo "Hello wrld from testing"
    - name: execute few commands
      run: |
         echo "Hello Massage1"
         echo "Application Name: ${{ env.APPLICATION_NAME }}"
    - name: Git clone my repo 
      uses: actions/checkout@v1
    - name: list files 
      run: ls -lah
  
  print: 
    runs-on: ubuntu-latest
    needs: [my_testings]
    steps:
      - name: print hello
        run: echo "Hello wrld from print"
      - name: print PKG name 
        run: echo " ${{ env.PACKAGE }}" 
      - name: test aws 
        run: aws --version 
