#-----------------------------------
#MYFirst  github actions 
#
#-----------------------------------
name: Demo-actions

on: 
   push:
     branches: 
        - master 

jobs:
  my_testings:
    runs-on: ubuntu-latest
    steps:
    - name: print hello
      run: echo "Hello wrld from testing"
  
  print: 
    runs-on: ubuntu-latest
    needs: [my_testings]
    steps:
      - name: print hello
        run: echo "Hello wrld from print"
